Feature/grouping can rotate
The-Chuck-Chuck/The-Chuck pull request #15
Opened 2024-11-15 07:07 UTC by Seongnam-si

# 작업 내용

- [x] 회전 방식 변경에 따라, 불필요한 로직 제거
- [x] 회전 대상 마우스 클릭시 회전 요소들 그룹화
- [x] 그룹화 된 요소들 외곽선 시각 변화 처리
- [x] 회전 대상에 맞게 회전축 시작점 동적으로 적용

## 목업 UI 화면

<img width="794" alt="스크린샷 2024-11-15 15 01 54" src="https://github.com/user-attachments/assets/cd7d9c3a-2dc0-41dd-9b6d-f092cb7c086d">

## 실제 구현 화면

<img width="397" alt="스크린샷 2024-11-15 15 02 25" src="https://github.com/user-attachments/assets/bb693d53-3a85-4249-9477-f20ec7f191fb">

# 참고 사항

### 기존 회전 방법
1. 마우스 클릭
2. LEFT, RIGHT 버튼 클릭으로 회전 그룹 지정
3. 다시 한번 LEFT, RIGHT 버튼 클릭으로 회전 시작
### 개선 방법
1. 마우스 클릭시 자동으로 회전 그룹 지정
2. LEFT, RIGHT 버튼 클릭으로 회전 시작

- 위와 같은 회전 방법 변경으로 인하여, 기존 로직중 사용하지 않는 부분 모두 제거

### 주요 변경점
1. SimulController 컴포넌트 버튼 핸들러 로직 단순화
2. utils 파일 연산 로직 단순화
3. 회전 그룹에 대한 그룹화 방식 변경

# 리뷰 반영 내용

리뷰 내용 반영 후 수정 내용 발생시 이 부분에 작성해 주세요.

2024-11-15 08:39 UTC, Frogman113 commented on src/components/CanvasPainter.jsx
> +    if (customAxis && currentRotationAngle !== rotationAngle) {
currentRotationAngle이 이전 main과 다르게 useState에서 useRef로 바뀌었네요 같은 목적이기는 하나 코드의 기능이 달라진 것이기 때문에 변수명으로 useRef임을 나타내야 맞을 것 같습니다.
두 가지 이유가 있습니다. 저희 팀 변수명 규칙에서 useRef가 들어가는 변수는 Ref를 항상 뒤에 붙여주었고, 이전부터 main 부터currentRotationAngle이 useState로 사용했기 때문에 팀원들에게 혼동을 줄 수 있다고 생각합니다.

2024-11-15 11:29 UTC, Frogman113 commented on src/components/CanvasPainter.jsx
> +  let groupedChuckItems = null;
CanvasPainter 컴포넌트를 살펴보니 groupedChuckItems, ungroupedChuckItems 변수들은 81번 줄 코드에서만 사용됩니다. 그렇다면 전역변수가 아닌 함수 내부 지역변수로 넣는 것이 맞다고 생각합니다.
전역으로 사용할 일이 없는데 전역변수로 선언하게 되는 경우 몇가지 문제점이 있습니다.

1. 암묵적 결합으로 인해 가독성이 저하될 수 있고, 의도치 않게 상태가 변경될 수 있습니다.

2. 지역 변수는 함수가 호출되어 실행되는 동안에만 유효하지만, 전역 변수는 애플리케이션이 종료되기 전까지 계속 유효합니다. 즉, 메모리 리소스 낭비가 심합니다.

3. 스코프 체인 상에서 마지막에 존재하기 때문에 전역 변수는 가장 마지막에 검색 됩니다. 이는 효율적인 측면에서 안 좋습니다.

4. 자바스크립트는 파일이 분리 되어도 하나의 전역 스코프를 공유하기 때문에 같은 파일 또는 다른 파일에서 동일한 이름으로 변수명을 지었을 때 오류가 발생합니다.

2024-11-15 11:48 UTC, Frogman113 commented on src/pages/Simulator.jsx
> +        clickedChuckInfo.position.y
clickedChuckInfo에서 척(삼각기둥)을 클릭 했을 때, 마지막 position.z를 받아와야 x, y, z를 정상적 받아 position을 이룰 것 같습니다.

2024-11-15 11:48 UTC, Frogman113 approved these changes

2024-11-15 12:08 UTC, Frogman113 requested changes
리뷰한 항목 수정 요청드립니다.

2024-11-15 14:11 UTC, miinje commented on src/components/Chuck.jsx
> +const Chuck = ({ position, color, onPointerDown, rotationAngle }) => {
Chuck이라는 컴포넌트를 Reverse와 분리하지 말고 하나의 컴포넌트 안에서 분기를 치는 게 어떨까요?`vertexArray`와 `shapeFace`  이 부분에 대해서 다른 함수로 처리한다든가 혹은 컴포넌트 내부에서 값을 삼항연산자로 조절하는 등의 방법이 있습니다. 
이렇게 생각한 이유는 크게 두 가지 정도 있습니다. 

- `vertexArray`와 `shapeFace` 값을 제외하면 동일한 로직을 가지고 있습니다. 코드가 반복되므로 유지보수가 비효율적입니다.
- 동일한 로직이 두 컴포넌트에 분리되어 있다면, 로직을 변경해야 할 때 두 곳 모두 수정해야 하므로 실수나 누락이 발생할 가능성이 높습니다.

밑에 관련된 내용을 다루는 사이트를 첨부드리겠습니다. 참고 부탁드려요.
[Don't repeat yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

2024-11-15 14:11 UTC, miinje commented on src/components/Chuck.jsx
> +const Chuck = ({ position, color, onPointerDown, rotationAngle }) => {
이 부분에 대해서는 로직이 모두 완성되고 난 후 리팩토링하는 방향으로 가도 좋을 것 같습니다!

2024-11-15 15:06 UTC, Seongnam-si commented on src/components/CanvasPainter.jsx
> +  const currentRotationAngle = useRef(0);
반영했습니다!

2024-11-15 15:06 UTC, Seongnam-si commented on src/components/CanvasPainter.jsx
> +    ungroupedChuckItems = chuckPositionsList
반영했습니다!

2024-11-15 15:06 UTC, Seongnam-si commented on src/pages/Simulator.jsx
> +        clickedChuckInfo.position.y
반영했습니다!

2024-11-15 15:08 UTC, Seongnam-si commented on src/components/Chuck.jsx
> +const Chuck = ({ position, color, onPointerDown, rotationAngle }) => {
해당 부분은 내일 아침에 다같이 만나서 상의 후 결과에 따라 이후 PR 내용에 반영하는 방향으로 갈게요!

2024-11-15 15:27 UTC, Seongnam-si commented
두분이 공통으로 코멘트 달아주신 내용에 대해 답변 드려요!!

제가 로직을 작성하며 조건을 잘못 작성하여 그럴수도 있지만, 현재는 동적으로 그룹화 되는 
Chuck과 ReverseChuck을 구성하기 위해서는 어떤 조건에 따라 기존에 있던 리스트에서 
분리 시키는 방법이 최선이라 생각했어요

그러기 위해서 나온 조건이 101 번째 줄 
`if (targetIndex !== null)` 이라는 조건, 이 조건에 따라 나온 결과를 JSX문 내부에서 다시 분기라는
방법을 사용했고,

그래서 if문 내부에서 선언한 변수는 외부에 있는 리턴문 내부 JSX문에서 접근이 불가능하기에,
외부 전역 범위로 빼두었고, 그러면 const로는 재할당이 불가능하기에 let 키워드를 사용했습니다

2024-11-15 15:28 UTC, Seongnam-si commented on src/components/CanvasPainter.jsx
> +  let groupedChuckItems = null;
두분이 동일한 부분에 코멘트 달아주셔서 아래에 추가 내용 작성했어요!!
참고 부탁드립니다

2024-11-15 15:28 UTC, Seongnam-si commented on src/components/CanvasPainter.jsx
> +    groupedChuckItems = chuckPositionsList
두분이 동일한 부분에 코멘트 달아주셔서 아래에 추가 내용 작성했어요!!
참고 부탁드립니다

2024-11-15 16:29 UTC, miinje commented on src/components/CanvasPainter.jsx
> +    ungroupedChuckItems = chuckPositionsList
확인했습니다! 감사합니다!

2024-11-15 16:29 UTC, miinje commented on src/components/CanvasPainter.jsx
> +  const currentRotationAngle = useRef(0);
확인했습니다! 감사합니다!

2024-11-15 16:31 UTC, miinje commented on src/components/CanvasPainter.jsx
> +    groupedChuckItems = chuckPositionsList
내용 확인했습니다! 내용에 대해 읽어 보니 코드를 이렇게 작성하신 것이 이해가 갑니다. 일단 이렇게 유지하고, 이후 리팩토링 과정에서 더 나은 방식이 있을지에 대해 고민해 보는 방향은 어떨까요?

2024-11-15 16:40 UTC, miinje approved these changes
변경사항 모두 확인했습니다! 수고하셨습니다!

2024-11-16 00:43 UTC, merged

2024-11-16 06:13 UTC, miinje commented on src/components/CanvasPainter.jsx
> +    groupedChuckItems = chuckPositionsList
아! 이 부분에 대해선 제가 착각한 것이 있었습니다. if문 안도 블록 스코프라 내부 안에서 선언하면 외부 스코프에서 사용할 수 없었겠군요. 이해했습니다!

2024-11-16 06:15 UTC, Frogman113 commented on src/components/CanvasPainter.jsx
> +  let groupedChuckItems = null;
저도 지역변수로 선언해도 props로 넘겨주는건 가능한줄 알았는데 또 알게되었습니다.